/*
 * This file includes functions generated by gpt-5 (OpenAI) with human edits/updates.
 * Reviewer: Nachmi Kott - Approved.
 */

'use client';

import { createContext, useContext, useMemo, useReducer, type ReactNode } from 'react';
import { floorPlannerReducer, initialFloorPlannerState } from './floor-planner/reducer';
import * as FloorPlannerActions from './floor-planner/actions';

export type Room = { id: string; name: string; x: number; y: number; w: number; h: number };
export type Rect = { id: string; x: number; y: number; w: number; h: number };

export type FloorPlannerState = {
  svgMarkup: string; 
  setSvg: (svg: string) => void;
  setLoading: (v: boolean) => void;
};

const FloorPlannerContext = createContext<FloorPlannerState | null>(null);

export const FloorPlannerProvider = ({ children }: { children: ReactNode }) => {
  const [state, dispatch] = useReducer(floorPlannerReducer, initialFloorPlannerState);

  const value = useMemo<FloorPlannerState>(() => ({
    ...state,
    setSvg: (svg) => dispatch(FloorPlannerActions.setSvg(svg)),
    setLoading: (v) => dispatch(FloorPlannerActions.setLoading(v)),
  }), [state]);

  return <FloorPlannerContext.Provider value={value}>{children}</FloorPlannerContext.Provider>;
};

export const useFloorPlannerContext = () => {
  const v = useContext(FloorPlannerContext);
  if (!v) throw new Error('usePlanner must be used within PlannerProvider');
  return v;
};
