/*
 * This file includes functions generated by gpt-5 (OpenAI) with human edits/updates.
 * Reviewer: Nachmi Kott - Approved.
 */


'use client';

import { createContext, useContext, useMemo, useReducer, type ReactNode } from 'react';
import { todoReducer, initialTodoState } from './todo/reducer';
import * as TodoActions from './todo/actions';

export type Todo = { id: string; title: string; done: boolean };

type TodoState = {
  items: Todo[];
  addMany: (titles: string[]) => void;
  markByTitle: (title: string, done: boolean) => void;
  renameByTitle: (oldTitle: string, newTitle: string) => void;
  removeByTitle: (title: string) => void;
  setAll: (next: Todo[]) => void;
};

const TodoContext = createContext<TodoState | null>(null);

export const TodoProvider = ({ children }: { children: ReactNode }) => {
  const [items, dispatch] = useReducer(todoReducer, initialTodoState);

  const value = useMemo<TodoState>(() => ({
    items,
    addMany: (titles) => dispatch(TodoActions.addMany(titles)),
    markByTitle: (title, done) => dispatch(TodoActions.markByTitle(title, done)),
    renameByTitle: (oldTitle, newTitle) => dispatch(TodoActions.renameByTitle(oldTitle, newTitle)),
    removeByTitle: (title) => dispatch(TodoActions.removeByTitle(title)),
    setAll: (next) => dispatch(TodoActions.setAll(next)),
  }), [items]);

  return <TodoContext.Provider value={value}>{children}</TodoContext.Provider>;
};

export const useTodoContext = () => {
  const v = useContext(TodoContext);
  if (!v) throw new Error('useTodos must be used within TodoProvider');
  return v;
};
