/*
 * This file includes functions generated by gpt-5 (OpenAI) with human edits/updates.
 * Reviewer: Nachmi Kott - Approved.
 */

'use client';

import { createContext, useContext, useMemo, useReducer, type ReactNode } from 'react';

export const TAB = {
  MAP: 'map',
  FLOOR: 'floor',
  TODOS: 'todos',
  IMAGE3D: 'image3d',
} as const;
export type TabKey = typeof TAB[keyof typeof TAB];

type UiState = {
  activeTab: TabKey;
};

type Action = { type: 'setActiveTab'; tab: TabKey };

const UiContext = createContext<{ state: UiState; setActiveTab: (tab: TabKey) => void } | null>(null);

const reducer = (state: UiState, action: Action): UiState => {
  switch (action.type) {
    case 'setActiveTab':
      return { ...state, activeTab: action.tab };
    default:
      return state;
  }
};

export const UiProvider = ({ children }: { children: ReactNode }) => {
  const [state, dispatch] = useReducer(reducer, { activeTab: TAB.MAP } as UiState);

  const value = useMemo(() => ({
    state,
    setActiveTab: (tab: TabKey) => dispatch({ type: 'setActiveTab', tab }),
  }), [state]);

  return <UiContext.Provider value={value}>{children}</UiContext.Provider>;
};

export const useUiContext = () => {
  const v = useContext(UiContext);
  if (!v) throw new Error('useUi must be used within UiProvider');
  return v;
};
