/*
 * This file includes functions generated by gpt-5 (OpenAI) with human edits/updates.
 * Reviewer: Nachmi Kott - Approved.
 */

import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";
import { MapProvider } from "./state/MapContext";
import { TodoProvider } from "./state/TodoContext";
import { FloorPlannerProvider } from "./state/FloorPlannerContext";
import { UiProvider } from "./state/UiContext";

export const metadata: Metadata = {
  title: "Cascadia JS Hackathon 2025",
  description: "Next.js app scaffold",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <header className="navbar">
          <div className="nav-inner">
            <div className="brand">The Clueless Crafter</div>
          </div>
        </header>
        <UiProvider>
          <MapProvider>
            <TodoProvider>
              <FloorPlannerProvider>
                {children}
              </FloorPlannerProvider>
            </TodoProvider>
          </MapProvider>
        </UiProvider>
      </body>
    </html>
  );
};

export default RootLayout;
