/*
 * This file includes functions generated by gpt-5 (OpenAI) without human edits/updates.
 * Reviewer: Nachmi Kott - Approved.
 */

import Chat from "./components/Chat";
import Tabs from "./components/Tabs";

const HomePage = () => {
  return (
    <main className="container split">
      <section className="pane left">
        <Tabs />
      </section>
      <section className="pane right">
        <Chat />
      </section>
    </main>
  );
};

export default HomePage;
